name: gospel-semantic-search-backend

services:
  db:
    container_name: db
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - db-data:/qdrant/storage
    restart: unless-stopped

  db-init:
    container_name: db-init
    build:
      context: ./db-init
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=6333
    restart: no

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # http://localhost:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=6333
    restart: unless-stopped

  # Uncomment this if you want to run a database operation
  # db-op:
  #   container_name: db-op
  #   build:
  #     context: ./db-op
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=6333
  #   restart: no

volumes:
  db-data:
